stabilize dht through data_channel
BNSnet/bns-node pull request #50
Opened 2022-03-02 10:53 UTC by Raytlty

use stabilize periodly, find successor and  update finger_table

2022-03-02 19:30 UTC, RyanKung commented on bns-core/src/types/ice_transport.rs
> +    fn new(signaler: Arc<Ch>, procedures: Arc<Procedures>) -> Self;
Transport is just ONLY for handling connection. Concrete logic should NOT attach to it.

2022-03-02 19:33 UTC, RyanKung commented on bns-core/src/dht/message.rs
> +    pub routing: Arc<StdMutex<Chord>>,
`Procedures` or `Successor` is NOT real role, they are virtual and should not include `Chord`, BTW, `Chord` is not routing, it's an algorithm helper and to manage statement for RING.

All function associated to `Procedures` or `Successor` should be implemented under Swarm.

2022-03-02 19:33 UTC, RyanKung commented on bns-core/src/lib.rs
> +#![allow(dead_code)]
Pls, Never do this, if a PR should fail CI, let it failed.

2022-03-02 19:37 UTC, RyanKung commented on bns-core/src/types/channel.rs
> +    pub fn from_action(action: ChordAction) -> Events {
Use `std::From` instead. And it should be a `TryFrom`.

2022-03-02 19:42 UTC, RyanKung requested changes
Cant merge yet

2022-03-03 01:54 UTC, Raytlty commented on bns-core/src/dht/message.rs
> +    pub routing: Arc<StdMutex<Chord>>,
`it's an algorithm helper and to manage statement for RING`
why chord cant use for ROUTING

2022-03-10 14:30 UTC, Raytlty commented
close this branch, will push another checkout from features/response-msg

2022-03-10 14:30 UTC, closed without merging